pedidos/apps/frontapp/urls.py
from xmlrpc import client
from django.contrib import admin
from django.urls import path 
from .views import *

app_name = 'front'
urlpatterns =[
    path('index/',inicioView.as_view(), name='index'),
    path('base/', baseView.as_view(), name = 'base'),
    path('base2/', base2View.as_view(), name= 'base2'),
    path('base3/', base3View.as_view(), name='base3'),
    path('login/', loginXView.as_view(), name='login'),
    path('loNuevo/', nuevoView.as_view(), name='loNuevo'),
    path('proOficina/', proOficinaView.as_view(), name='proOficina'),
    path('carrito/', carritoView.as_view(), name='carrito'),
    
]

pedidos/apps/negocioapp/urls.py
from xmlrpc import client
from django.contrib import admin
from django.urls import path 
from .views import *

app_name = 'negocio'
urlpatterns =[
    path('cliente/', clientesView.as_view(), name='clientes'),
    path('pedidos/', pedidosView.as_view(), name='pedidos'),
    path('inventario/', inventarioView.as_view(), name='inventario'),
    path('detalleArt/', detalleArtView.as_view(), name='detalleArt'),
]

pedidos/pedidos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('frontapp/', include('apps.frontapp.urls')),
    path('negocioapp/', include('apps.negocioapp.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

pedidos/apps/frontapp/models.py
from django.db import models

# Create your models here.

pedidos/apps/negocioapp/models.py
from django.db import models

# Create your models here.

pedidos/apps/frontapp/views.py
from django.shortcuts import render
from django.views.generic import *
from django.contrib.auth.views import *

# Create your views here.
class baseView (TemplateView):
    template_name = 'base.html'

class base2View(TemplateView):
    template_name = "base2.html"

class base3View(TemplateView):
    template_name = "base3.html"

class inicioView (TemplateView):
    template_name = 'index.html'

class nuevoView(TemplateView):
    template_name = 'loNuevo.html'

class loginXView(LoginView):
    template_name = 'registro/login.html'

class proOficinaView(TemplateView):
    template_name = 'proOficina.html'

class carritoView(TemplateView):
    template_name = 'carrito.html'

    

pedidos/apps/negocioapp/views.py
from tempfile import template
from django.shortcuts import render
from django.views.generic import *
from django.contrib.auth.views import *

# Create your views here.
class pedidosView(TemplateView):
    template_name = 'pedidos.html'

class clientesView(TemplateView):
    template_name = 'cliente.html'

class inventarioView(TemplateView):
    template_name = 'inventario.html'

class detalleArtView(TemplateView):
    template_name = 'detalleArt.html'

pedidos/apps/frontapp/templates/base3.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Template Mo">
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900" rel="stylesheet">

    {%block titulo%}<title>Productos</title>{%endblock%}

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">


    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="{% static 'assets/css/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/templatemo-edu-meeting.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/owl.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/lightbox.css' %}">

<!--

TemplateMo 569 Edu Meeting

https://templatemo.com/tm-569-edu-meeting

-->
  </head>

<body>

   

  <!-- Sub Header -->
  

  <!-- ***** Header Area Start ***** -->
  <header class="header-area header-sticky">
      <div class="container">
          <div class="row">
              <div class="col-12">
                  <nav class="main-nav">
                      <!-- ***** Logo Start ***** -->
                      {%block tituloLogo%}
                      <a href="#" class="logo">
                          Edu Meeting
                      </a>
                      {%endblock%}
                      <!-- ***** Logo End ***** -->
                      <!-- ***** Menu Start ***** -->
                      {%block menu%}
                      <ul class="nav">
                        <li ><a href="{% url 'front:index'%}" >Inicio</a></li>
                        <li><a href="{% url 'front:loNuevo'%}">Lo Nuevo</a></li>
                        <li class="scroll-to-section"><a href="">Como Hacer Pedidos</a></li>
                        <li class="has-sub">
                            <a href="javascript:void(0)" class="active">Productos</a>
                            <ul class="sub-menu">
                                <li><a href="{% url 'front:proOficina'%}">Oficina</a></li>
                                <li><a href="#">Habitaciones</a></li>
                                <li><a href="#">Cocina</a></li>
                            </ul>
                        </li>
                        <li class=""><a href="#">Ofertas</a></li> 
                        <li class=""><a href="{% url 'front:login'%}">LOGIN</a></li> 
                        <li><a  href="{% url 'front:carrito'%}"><img src="{% static 'assets/images/carritoimg.png'%}" alt="Carrito"></a></li>
                    </ul>        
                    <a class='menu-trigger'>
                        <span>Menu</span>
                    </a>
                      {%endblock%}
                      <!-- ***** Menu End ***** -->
                  </nav>
              </div>
          </div>
      </div>
  </header>
  <!-- ***** Header Area End ***** -->

  {%block encabezado%}
  
  {%endblock%}
{%block Productos%}

  <section class="meetings-page" id="meetings">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div class="row">
            <div class="col-lg-12">
              <!-- <div class="filters">
                <ul>
                  <li data-filter="*"  class="active">All Meetings</li>
                  <li data-filter=".soon">Soon</li>
                  <li data-filter=".imp">Important</li>
                  <li data-filter=".att">Attractive</li>
                </ul>
              </div>
            </div> -->
            <div class="col-lg-12">
              <div class="row grid">
                <div class="col-lg-4 templatemo-item-col all soon">
                  <div class="meeting-item">
                    <div class="thumb">
                      <div class="price">
                        <span>$14.00</span>
                      </div>
                      <a href="meeting-details.html"><img src="{% static 'assets/images/meeting-01.jpg'%}" alt=""></a>
                    </div>
                    <div class="down-content">
                      <div class="date">
                        <h6>Nov <span>12</span></h6>
                      </div>
                      <a href="meeting-details.html"><h4>New Lecturers Meeting</h4></a>
                      <p>Morbi in libero blandit lectus<br>cursus ullamcorper.</p>
                    </div>
                  </div>
                </div>
                <div class="col-lg-4 templatemo-item-col all imp">
                  <div class="meeting-item">
                    <div class="thumb">
                      <div class="price">
                        <span>$22.00</span>
                      </div>
                      <a href="meeting-details.html"><img src="assets/images/meeting-02.jpg" alt=""></a>
                    </div>
                    <div class="down-content">
                      <div class="date">
                        <h6>Nov <span>14</span></h6>
                      </div>
                      <a href="meeting-details.html"><h4>Online Teaching Techniques</h4></a>
                      <p>Morbi in libero blandit lectus<br>cursus ullamcorper.</p>
                    </div>
                  </div>
                </div>
                <div class="col-lg-4 templatemo-item-col all soon">
                  <div class="meeting-item">
                    <div class="thumb">
                      <div class="price">
                        <span>$24.00</span>
                      </div>
                      <a href="meeting-details.html"><img src="assets/images/meeting-03.jpg" alt=""></a>
                    </div>
                    <div class="down-content">
                      <div class="date">
                        <h6>Nov <span>16</span></h6>
                      </div>
                      <a href="meeting-details.html"><h4>Network Teaching Concept</h4></a>
                      <p>Morbi in libero blandit lectus<br>cursus ullamcorper.</p>
                    </div>
                  </div>
                </div>
                <div class="col-lg-4 templatemo-item-col all att">
                  <div class="meeting-item">
                    <div class="thumb">
                      <div class="price">
                        <span>$32.00</span>
                      </div>
                      <a href="meeting-details.html"><img src="assets/images/meeting-04.jpg" alt=""></a>
                    </div>
                    <div class="down-content">
                      <div class="date">
                        <h6>Nov <span>18</span></h6>
                      </div>
                      <a href="meeting-details.html"><h4>Online Teaching Tools</h4></a>
                      <p>Morbi in libero blandit lectus<br>cursus ullamcorper.</p>
                    </div>
                  </div>
                </div>
                <div class="col-lg-4 templatemo-item-col all att">
                  <div class="meeting-item">
                    <div class="thumb">
                      <div class="price">
                        <span>$34.00</span>
                      </div>
                      <a href="meeting-details.html"><img src="assets/images/meeting-02.jpg" alt=""></a>
                    </div>
                    <div class="down-content">
                      <div class="date">
                        <h6>Nov <span>22</span></h6>
                      </div>
                      <a href="meeting-details.html"><h4>New Teaching Techniques</h4></a>
                      <p>Morbi in libero blandit lectus<br>cursus ullamcorper.</p>
                    </div>
                  </div>
                </div>
                <div class="col-lg-4 templatemo-item-col all imp">
                  <div class="meeting-item">
                    <div class="thumb">
                      <div class="price">
                        <span>$45.00</span>
                      </div>
                      <a href="meeting-details.html"><img src="assets/images/meeting-03.jpg" alt=""></a>
                    </div>
                    <div class="down-content">
                      <div class="date">
                        <h6>Nov <span>24</span></h6>
                      </div>
                      <a href="meeting-details.html"><h4>Technology Conference</h4></a>
                      <p>TemplateMo is the best website<br>when it comes to Free CSS.</p>
                    </div>
                  </div>
                </div>
                


              </div>
            </div>
            <div class="col-lg-12">
              <div class="pagination">
                <ul>
                  <li><a href="#">1</a></li>
                  <li class="active"><a href="#">2</a></li>
                  <li><a href="#">3</a></li>
                  <li><a href="#"><i class="fa fa-angle-right"></i></a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="footer">
      <p>Copyright © 2022 Edu Meeting Co., Ltd. All Rights Reserved. 
          <br>Design: <a href="https://templatemo.com/page/1" target="_parent" title="website templates">TemplateMo</a></p>
    </div>
  </section>
  {%endblock%}


  <!-- Scripts -->
  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'vendor/jquery/jquery.min.js'%}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js'%}"></script>

  <script src="{% static 'assets/js/isotope.min.js'%}"></script>
  <script src="{% static 'assets/js/owl-carousel.js'%}"></script>
  <script src="{% static 'assets/js/lightbox.js'%}"></script>
  <script src="{% static 'assets/js/tabs.js'%}"></script>
  <script src="{% static 'assets/js/video.js'%}"></script>
  <script src="{% static 'assets/js/slick-slider.js'%}"></script>
  <script src="{% static 'assets/js/custom.js'%}"></script>
    <script>
        //according to loftblog tut
        $('.nav li:first').addClass('active');

        var showSection = function showSection(section, isAnimate) {
          var
          direction = section.replace(/#/, ''),
          reqSection = $('.section').filter('[data-section="' + direction + '"]'),
          reqSectionPos = reqSection.offset().top - 0;

          if (isAnimate) {
            $('body, html').animate({
              scrollTop: reqSectionPos },
            800);
          } else {
            $('body, html').scrollTop(reqSectionPos);
          }

        };

        var checkSection = function checkSection() {
          $('.section').each(function () {
            var
            $this = $(this),
            topEdge = $this.offset().top - 80,
            bottomEdge = topEdge + $this.height(),
            wScroll = $(window).scrollTop();
            if (topEdge < wScroll && bottomEdge > wScroll) {
              var
              currentId = $this.data('section'),
              reqLink = $('a').filter('[href*=\\#' + currentId + ']');
              reqLink.closest('li').addClass('active').
              siblings().removeClass('active');
            }
          });
        };

        $('.main-menu, .responsive-menu, .scroll-to-section').on('click', 'a', function (e) {
          e.preventDefault();
          showSection($(this).attr('href'), true);
        });

        $(window).scroll(function () {
          checkSection();
        });
    </script>
</body>


  </body>

</html>

pedidos/apps/frontapp/templates/carrito.html
{% extends 'base3.html' %}
{% load static %}

{%block titulo%}<title>Carrito</title>{%endblock%}
{%block menu%}
                      <ul class="nav">
                        <li ><a href="{% url 'front:index'%}" >Inicio</a></li>
                        <li><a href="{% url 'front:loNuevo'%}">Lo Nuevo</a></li>
                        <li class="scroll-to-section"><a href="">Como Hacer Pedidos</a></li>
                        <li class="has-sub">
                            <a href="javascript:void(0)" >Productos</a>
                            <ul class="sub-menu">
                                <li><a href="{% url 'front:proOficina'%}">Oficina</a></li>
                                <li><a href="#">Habitaciones</a></li>
                                <li><a href="#">Cocina</a></li>
                            </ul>
                        </li>
                        <li class=""><a href="#">Ofertas</a></li> 
                        <li class=""><a href="{% url 'front:login'%}">LOGIN</a></li> 
                        <li><a href="{% url 'front:carrito'%}"><img src="{% static 'assets/images/carritoimg.png'%}" alt="Carrito"></a></li>
                    </ul>        
                    <a class='menu-trigger'>
                        <span>Menu</span>
                    </a>
                      {%endblock%}

{%block tituloLogo%}
<a href="#" class="logo">
    Carrito
</a>
{%endblock%}

<!-- <div class="date">
    <h6>Nov <span>24</span></h6>
  </div> -->
  {%block encabezado%}
  <section class="heading-pageCa header-text" id="top">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
            <h2>Carrito de compras</h2>
          
        </div>
      </div>
    </div>
  </section>
  {%endblock%}

{%block Productos%}
<section class="contact-us" id="contact">
    <div class="container">
      <div class="row">
        <div class="col-lg-9 align-self-center">
          <div class="row">
            <div class="col-lg-12">
              <form id="contact" action="" method="post">
                <div class="row">
                  <div class="col-lg-12">
                    <h2>Productos Agregados</h2>
                  </div>

                  <table class="table table-hover">
                    <thead>
                      <tr>
                        <th scope="col">Cantidad</th>
                        <th scope="col">Nombre Producto</th>
                        <th scope="col">Monto Individual</th>
                        <th scope="col">Monto Total</th>
                        <th scope="col"></th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <th scope="row">2</th>
                        <td>Escritorio de madera</td>
                        <td>Q 800</td>
                        <td>Q 1600</td>
                        <td><a href="#">Quitar</a></td>
                      </tr>
                      <tr>
                        <th scope="row">1</th>
                        <td>Mueble para Microondas</td>
                        <td>Q 1500</td>
                        <td>Q 1500</td>
                        <td><a href="#">Quitar</a></td>
                      </tr>
                      <tr>
                        <th scope="row">3</th>
                        <td>Estanterias de metal</td>
                        <td>Q 500</td>
                        <td>Q 1500</td>
                        <td><a href="#">Quitar</a></td>
                      </tr>
                    </tbody>

                    <tr>
                        <th scope="row">Total a Pagar</th>
                        <td></td>
                        <td></td>
                        <td>Q 4600</td>
                        <td></td>
                      </tr>
                  </table>
                  
                  <div class="col-lg-12">
                    <fieldset>
                      <button type="submit" id="form-submit" class="button">Pagar</button>
                      <button type="submit" id="form-submit" class="button">Seguir comprando</button>
                    </fieldset>                                         
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
        <div class="col-lg-3">
            <div class="right-info">
                <ul>
                    <li>
                      <h6>Instrucciones</h6>
                      <span>......</span>
                    </li>
                    
                  </ul>
            </div>
          </div>
      </div>
    </div>
    



    

    <div class="footer">
        <p>Footer
            <br>Problemas: <a href="https://templatemo.com" target="_parent" title="free css templates">Contacto</a></p>
      </div>
  </section>

  {%endblock%}

pedidos/apps/frontapp/templates/index.html
{% extends 'base.html' %}
{% load static %}


    {%block titulo%}<title>Inicio</title>{%endblock%}


    
    {%block logo%}
                      <a href="#" class="logo">
                          Tus pedidos
                      </a>
    {%endblock%}

    {%block bannersM %}
    {%endblock%}
  
    {% block instrucciones%}
    {%endblock%}

    {%block ofertas%}
    {%endblock%}

    {%block datos%}
    {%endblock%}
    
    {%block contacto%}
    {%endblock%}

pedidos/apps/frontapp/templates/loNuevo.html
{% extends 'base.html' %}
{% load static %}
{%block titulo%}<title>Nuevos</title>{%endblock%}



    
{%block logo%}
                  <a href="" class="logo">
                      Lo nuevo
                  </a>
{%endblock%}
{%block menu%}
<ul class="nav">
  <li ><a href="{% url 'front:index'%}" >Inicio</a></li>
  <li><a href="{% url 'front:loNuevo'%}" class="active">Lo Nuevo</a></li>
  <li class="scroll-to-section"><a href="">Como Hacer Pedidos</a></li>
  <li class="has-sub">
      <a href="javascript:void(0)">Productos</a>
      <ul class="sub-menu">
          <li><a href="{% url 'front:proOficina'%}">Oficina</a></li>
          <li><a href="#">Habitaciones</a></li>
          <li><a href="#">Cocina</a></li>
      </ul>
  </li>
  <li class=""><a href="#">Ofertas</a></li> 
  <li class=""><a href="{% url 'front:login'%}">LOGIN</a></li> 
  <li><a href="{% url 'front:carrito'%}"><img src="{% static 'assets/images/carritoimg.png'%}" alt="Carrito"></a></li>
</ul>        
<a class='menu-trigger'>
  <span>Menu</span>
</a>
{%endblock%}
{%block encabezadoBanner%}
{%endblock%}

{%block VideoPrincipal%}

                
  <section class="our-courses" id="courses">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div class="section-heading">
            <h2>Nuevos Materiales de Oficina</h2>
          </div>
        </div>
        <div class="col-lg-12">
          <div class="owl-courses-item owl-carousel">
            <div class="item">
              <img src="https://cemacogt.vteximg.com.br/arquivos/ids/453834-1100-1100/1039951_1.jpg?v=637945730922570000" alt="Course One">
              <div class="down-content">
                <h4>Escritorios de aluminio y Madera</h4>
                <div class="info">
                  <div class="row">
                    <div class="col-8">
                      <ul>
                        <li><i class="fa fa-star"></i></li>
                        <li><i class="fa fa-star"></i></li>
                        <li><i class="fa fa-star"></i></li>
                        <li><i class="fa fa-star"></i></li>
                        <li><i class="fa fa-star"></i></li>
                      </ul>
                    </div>
                    <div class="col-4">
                       <span>$160</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="item">
              <img src="https://cemacogt.vteximg.com.br/arquivos/ids/316774-250-250/984016_1.jpg?v=637951010966100000" alt="Course Two">
              <div class="down-content">
                <h4>Sillas de rotativas y estaticas de distintos colores</h4>
                <div class="info">
                  <div class="row">
                    <div class="col-8">
                      <ul>
                        <li><i class="fa fa-star"></i></li>
                        <li><i class="fa fa-star"></i></li>
                        <li><i class="fa fa-star"></i></li>
                      </ul>
                    </div>
                    <div class="col-4">
                       <span>$180</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="item">
              <img src="https://d1cft8rz0k7w99.cloudfront.net/n/4/c/4/a/4c4a9a398860c68f0b61d61a9327d0b9ea0a2b56_ShelvingUnits_441194_01.png" alt="">
              <div class="down-content">
                <h4>Estanterias de varios niveles y tamanos</h4>
                <div class="info">
                  <div class="row">
                    <div class="col-8">
                      <ul>
                        <li><i class="fa fa-star"></i></li>
                        <li><i class="fa fa-star"></i></li>
                        <li><i class="fa fa-star"></i></li>
                        <li><i class="fa fa-star"></i></li>
                      </ul>
                    </div>
                    <div class="col-4">
                       <span>$140</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="item">
              <img src="https://www.induya.com.co/wp-content/uploads/2018/09/untitled.18.png" alt="">
              <div class="down-content">
                <h4>Archivadores para ofician de distintos nivels</h4>
                <div class="info">
                  <div class="row">
                    <div class="col-8">
                      <ul>
                        <li><i class="fa fa-star"></i></li>
                        <li><i class="fa fa-star"></i></li>
                        <li><i class="fa fa-star"></i></li>
                        <li><i class="fa fa-star"></i></li>
                        <li><i class="fa fa-star"></i></li>
                      </ul>
                    </div>
                    <div class="col-4">
                       <span>$120</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="item">
              <img src="https://images-eu.ssl-images-amazon.com/images/I/41TxwLbNTSL.jpg" alt="">
              <div class="down-content">
                <h4>Mostradores con nuevos disenos y tamanos</h4>
                <div class="info">
                  <div class="row">
                    <div class="col-8">
                      <ul>
                        <li><i class="fa fa-star"></i></li>
                        <li><i class="fa fa-star"></i></li>
                        <li><i class="fa fa-star"></i></li>
                        <li><i class="fa fa-star"></i></li>
                        <li><i class="fa fa-star"></i></li>
                      </ul>
                    </div>
                    <div class="col-4">
                       <span>$250</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>          
           
           
          </div>
        </div>
      </div>
    </div>


    <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <div class="section-heading">
              <h2>Nuevos Materiales de Oficina</h2>
            </div>
          </div>
          <div class="col-lg-12">
            <div class="owl-courses-item owl-carousel">
              <div class="item">
                <img src="https://cemacogt.vteximg.com.br/arquivos/ids/453834-1100-1100/1039951_1.jpg?v=637945730922570000" alt="Course One">
                <div class="down-content">
                  <h4>Escritorios de aluminio y Madera</h4>
                  <div class="info">
                    <div class="row">
                      <div class="col-8">
                        <ul>
                          <li><i class="fa fa-star"></i></li>
                          <li><i class="fa fa-star"></i></li>
                          <li><i class="fa fa-star"></i></li>
                          <li><i class="fa fa-star"></i></li>
                          <li><i class="fa fa-star"></i></li>
                        </ul>
                      </div>
                      <div class="col-4">
                         <span>$160</span>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="item">
                <img src="https://cemacogt.vteximg.com.br/arquivos/ids/316774-250-250/984016_1.jpg?v=637951010966100000" alt="Course Two">
                <div class="down-content">
                  <h4>Sillas de rotativas y estaticas de distintos colores</h4>
                  <div class="info">
                    <div class="row">
                      <div class="col-8">
                        <ul>
                          <li><i class="fa fa-star"></i></li>
                          <li><i class="fa fa-star"></i></li>
                          <li><i class="fa fa-star"></i></li>
                        </ul>
                      </div>
                      <div class="col-4">
                         <span>$180</span>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="item">
                <img src="https://d1cft8rz0k7w99.cloudfront.net/n/4/c/4/a/4c4a9a398860c68f0b61d61a9327d0b9ea0a2b56_ShelvingUnits_441194_01.png" alt="">
                <div class="down-content">
                  <h4>Estanterias de varios niveles y tamanos</h4>
                  <div class="info">
                    <div class="row">
                      <div class="col-8">
                        <ul>
                          <li><i class="fa fa-star"></i></li>
                          <li><i class="fa fa-star"></i></li>
                          <li><i class="fa fa-star"></i></li>
                          <li><i class="fa fa-star"></i></li>
                        </ul>
                      </div>
                      <div class="col-4">
                         <span>$140</span>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="item">
                <img src="https://www.induya.com.co/wp-content/uploads/2018/09/untitled.18.png" alt="">
                <div class="down-content">
                  <h4>Archivadores para ofician de distintos nivels</h4>
                  <div class="info">
                    <div class="row">
                      <div class="col-8">
                        <ul>
                          <li><i class="fa fa-star"></i></li>
                          <li><i class="fa fa-star"></i></li>
                          <li><i class="fa fa-star"></i></li>
                          <li><i class="fa fa-star"></i></li>
                          <li><i class="fa fa-star"></i></li>
                        </ul>
                      </div>
                      <div class="col-4">
                         <span>$120</span>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="item">
                <img src="https://images-eu.ssl-images-amazon.com/images/I/41TxwLbNTSL.jpg" alt="">
                <div class="down-content">
                  <h4>Mostradores con nuevos disenos y tamanos</h4>
                  <div class="info">
                    <div class="row">
                      <div class="col-8">
                        <ul>
                          <li><i class="fa fa-star"></i></li>
                          <li><i class="fa fa-star"></i></li>
                          <li><i class="fa fa-star"></i></li>
                          <li><i class="fa fa-star"></i></li>
                          <li><i class="fa fa-star"></i></li>
                        </ul>
                      </div>
                      <div class="col-4">
                         <span>$250</span>
                      </div>
                    </div>
                  </div>
                </div>
              </div>          
             
             
            </div>
          </div>
        </div>
      </div>

   

  </section>

  
          
{%endblock%}

{%block informativas%}
{%endblock%}


{%block bannersM %}
{%endblock%}

{% block instrucciones%}
{%endblock%}

{%block ofertas%}
{%endblock%}

{%block datos%}
{%endblock%}

{%block contacto%}
{%endblock%}